import "../styles/globals.css";
import Footer from "./Footer";
import Header from "./Header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
      <Header/>
      
        <div className="max-w-6xl mx-auto">
          {children}
        </div >
         <Footer />
        </body>
    </html>
  )
}
